apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: manager-priority-class
  namespace: system
  labels:
    app.kubernetes.io/name: kyma-companion-manager-priority-class
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component:  kyma-companion-manager
    app.kubernetes.io/part-of:    kyma-companion-manager
value: 2000000
globalDefault: false
description: "Scheduling priority of the Eventing-Manager module. Must not be blocked by unschedulable user workloads."
