apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager
  namespace: system
  labels:
    app.kubernetes.io/name: kyma-companion-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: kyma-companion-manager
    app.kubernetes.io/part-of: kyma-companion-manager
