apiVersion: operator.kyma-project.io/v1alpha1
kind: Companion
metadata:
  labels:
    app.kubernetes.io/name: default
    app.kubernetes.io/component: kyma-companion-manager
    app.kubernetes.io/part-of: kyma-companion-manager
  name: default
  namespace: kyma-system
spec:
  aicore: 
    secret: ai-core/aicore
  hanaCloud:
    secret: companion/hana-cloud
  redis:
    secret: companion/redis
  companion:
    secret: companion/aicore
    replicas:
      min: 1
      max: 3
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 256Mi