apiVersion: operator.kyma-project.io/v1alpha1
kind: Companion
metadata:
  name: companion-manager
  namespace: kyma-system
spec:
  aicore:
    secret:
      name: ai-core
      namespace: ai-core
  companion:
    replicas:
      min: 1
      max: 3
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 256Mi
    secret:
      name: companion
      namespace: ai-core
  hanaCloud:
    secret:
      name: companion
      namespace: hana-cloud
  redis:
    secret:
      name: companion
      namespace: redis
