apiVersion: operator.kyma-project.io/v1alpha1
kind: Companion
metadata:
  labels:
    app.kubernetes.io/name: kyma-companion-manager
    app.kubernetes.io/managed-by: kustomize
  name: companion-sample
spec:
  # TODO(user): Add fields here
