name: test

on:
  push:
    branches:
      - main
      - "release-**"
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "sec-scanners-config.yaml"
      - CODEOWNERS
      - LICENSE
      - LICENSES
      - OWNERS
      - OWNERS_ALIASES
      - PROJECT
  pull_request:
    branches:
      - main
      - "release-**"
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "sec-scanners-config.yaml"
      - CODEOWNERS
      - LICENSE
      - LICENSES
      - OWNERS
      - OWNERS_ALIASES
      - PROJECT

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod" # This uses the Go version defined in the mod file, in contrast to setting a defined version.

      - name: Sync Go dependencies
        run: |
          go mod vendor

      - name: Run tests
        run: |
          make test
